### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by 33mhz** [dusterio/link-preview#1]
I was sort of blindly hoping this would be a nice tool for detecting if a site exists at an address, but it just takes a long time and then times out. Would that be an in-scope feature to add, or should I use more traditional means for that?

**Comment by dusterio** [comment]
Hmm, this could be a good feature, yes! I think I will implement it this week

**Comment by dusterio** [comment]
I have just added proper exceptions and timeout settings. However, since cURL is used behind Guzzle – I can't say whether the error was DNS or network related. It's just yes or no - good link or dead link :)

**Comment by 33mhz** [comment]
Thanks. Spot-on. :)
