### ISSUE TITLE
403 Forbidden.  Please advise a good workaround for this.

### ISSUE THREAD

**Issue by imonoid** [dusterio/link-preview#15]
Encountered this error on a certain link I tried.  I would like to know if there is a work around for websites that give this error when you try to get  a link preview from it.  I have tested the link in both FB and LinkedIn, and both were able to retrieve the previews perfectly.

This is the code I am using to test:

      $previewClient = new Client($url);
      $previewClient->getParser('general')->getReader()->config(['connect_timeout' => 10, 'allow_redirects' => ['max' => 5]]);
      try {
          $preview = $previewClient->getPreview('general');
      } catch (\Dusterio\LinkPreview\Exceptions\ConnectionErrorException $e) {
          $preview = $e->getMessage();
      } catch (\Dusterio\LinkPreview\Exceptions\MalformedUrlException $e) {
          $preview = $e->getMessage();
      } catch (\GuzzleHttp\Exception\ClientException $e) {
          $preview = $e->getMessage();
      }
      
      $this->p($preview);

Thank you!

**Comment by JCarlosR** [comment]
@imonoid Hi. Did you find a solution?

The HtmlParser (general) gives me a 403 error for some links.

**Comment by geoffrex** [comment]
Had the same problem, turns out (at least in my case) that some pages return a 403 if the user agent is missing. I added the current user's user agent, but other values will probably work, too.

`$previewClient->getParser("general")->getReader()->config(["headers" => ["User-Agent" => @$_SERVER["HTTP_USER_AGENT"]]]);;`

**Comment by dusterio** [comment]
I added a default user agent as well
