### ISSUE TITLE
Inconsistent examples

### ISSUE THREAD

**Issue by 33mhz** [dusterio/link-preview#2]
Sometimes the examples refer to `$client`, sometimes to `$previewClient`.

I'm trying to test output with this:

```
$previewClient = new Client($url);
$previewClient->getParser('general')->getReader()->config(['connect_timeout' => 10, 'allow_redirects' => ['max' => 5]]);
try {
    $preview = $previewClient->getPreview('general');
} catch (\Dusterio\LinkPreview\Exceptions\ConnectionErrorException $e) {
    $preview = false;
} catch (\Dusterio\LinkPreview\Exceptions\MalformedUrlException $e) {
    $preview = false;
}
```

... and it's giving "Fatal error: Uncaught Error: Call to undefined method Dusterio\LinkPreview\Client::getParser()". It also gives fatals for uncaught exceptions. :(

**Comment by dusterio** [comment]
Hmm, maybe I forgot to push the changes or to tag the new version, sorry for this! :) I will check later today

**Comment by dusterio** [comment]
Ok, I tagged a new version (1.2.6), just run 'composer update' and your code will start working - I verified myself!

**Comment by 33mhz** [comment]
Thanks! The readme still seems inconsistent in [this example](https://github.com/dusterio/link-preview#timeouts-and-errors) on what `$client` is referring to -- but it is working for me.

**Comment by dusterio** [comment]
oops, you are right - I've just updated the readme, thanks for the heads up!
