### ISSUE TITLE
This documents not working!

### ISSUE THREAD

**Issue by hasnatbabur** [dusterio/link-preview#22]
I installed this library by composer in Laravel project.

I found the document is totally different and not working at all!

Error: Class 'Dusterio\LinkPreview\Client' not found!

Seems like composer still installing old kasp3r/link-preview package.

Also Laravel extra classes not working!

Can you please help? Thanks

**Comment by infostreams** [comment]
For what it's worth the code in the README is wrong. I use the library like this

```php
    function linkpreview($url) {
        $client = new \Dusterio\LinkPreview\LinkPreview($url);
        $parsed = $client->getParsed();

        if (count($parsed) > 0) {
            $preview = current($parsed);

            return [
                'title'       => $preview->getTitle(),
                'description' => $preview->getDescription(),
                'image'       => $preview->getImage(),
                'url'         => $preview->getUrl(),
                'realUrl'     => $preview->getRealUrl(),
            ];
        }

        return [];
    }
```

**Comment by christophermiles** [comment]
@infostreams Do you know if there is a way to set the timeout and redirect values as in the documentation?

**Comment by infostreams** [comment]
No, I'm sorry, I don't. 

I do know that you have to check the return value of `$preview->getTitle()`, because it can be an empty string. I found out because a user wanted to generate a link preview of a PDF document, which obviously doesn't work. In that case I've adjusted 'title' to return `basename($url)`, which is better than nothing. Saved you a bug.

**Comment by romansidorov** [comment]
> No, I'm sorry, I don't.
> 
> I do know that you have to check the return value of `$preview->getTitle()`, because it can be an empty string. I found out because a user wanted to generate a link preview of a PDF document, which obviously doesn't work. In that case I've adjusted 'title' to return `basename($url)`, which is better than nothing. Saved you a bug.

Hi! Is the package working for you on Laravel 7?

**Comment by infostreams** [comment]
I don't know, haven't upgraded yet.

**Comment by EfdalAlper** [comment]
i share my usage for u (for ur save time),

`<?php
$re = '/(?im)\b(?:https?:\/\/)?(?:w{3}\.)?youtu(?:be)?\.(?:com|be)\/(?:(?:\??v=?i?=?\/?)|watch\?vi?=|watch\?.*?&v=|embed\/|)([A-Z0-9_-]{11})\S*(?=\s|$)/';
$str = 'http://youtube.com/v/tFad5gHoBjY';
preg_match_all($re, $link, $matches, PREG_SET_ORDER, 0);

$setvideoembedd = NULL;
var_dump($matches);
if (!isset($matches[0][1])) {
    //$setvideoembedd = $matches[0][1];
}else {
$setvideoembedd = $matches[0][1];
}

if (strlen($setvideoembedd) == 0){

}else {
  echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/'.$setvideoembedd.'" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
}

if (!filter_var($link, FILTER_VALIDATE_URL)) {
  return response()->json(['msg'=>'Invalid Link'], 422);
}
$previewClient = new \Dusterio\LinkPreview\Client($link);
$preview = $previewClient->getPreview('general');
$preview=$preview->toArray();

$imagecoverarray=$preview['cover'];
$imagearray=$preview['images'];
$descriptionarray=$preview['description'];
$titlearray=$preview['title'];

if (isset($imagecoverarray) && (strlen($imagecoverarray))) {
  $previewimage = $imagecoverarray;
}elseif (isset($imagearray[1]) && (strlen($imagearray[1]))){
  $previewimage = $imagearray[1];
} else {
  $previewimage = '/public/img/blog-design.png';
}

if (isset($descriptionarray) && (strlen($descriptionarray))) {
    $previewdescription = Str::substr($descriptionarray, 0, 400);
  } else {
    $previewdescription = 'its not working';
  }

  if (isset($titlearray) && (strlen($titlearray))) {
    $previewtitle=$titlearray;
  }  else {
     $previewtitle = 'Onizleme için Başlık Bulunamadı';
   }
?>
<div class="row">
  <div class="col-md-4">
    <div class="linkcover">
        <img src="{{ $previewimage }}" alt="" title="" width="150"/>
    </div>
  </div>
  <div class="col-md-8">
      <h3>{{ $previewtitle }}</h3>
      <p>{{ $previewdescription }}</p>
  </div>
</div>`

**Comment by C0kkie** [comment]
I have the same issue:

Class 'Dusterio\LinkPreview\LinkPreview' not found with alravel 8

**Comment by romansidorov** [comment]
> I have the same issue:
> 
> Class 'Dusterio\LinkPreview\LinkPreview' not found with alravel 8

The same problem is on Laravel 7 too.

**Comment by C0kkie** [comment]
Cuz looks like for some guys its working

**Comment by C0kkie** [comment]
Nobody? Is this package not maintained anymore?

**Comment by dusterio** [comment]
@C0kkie what's the problem? :)

**Comment by C0kkie** [comment]
@dusterio  I try to get it working on laravel 8 but i always get class not found. See here https://github.com/dusterio/link-preview/issues/31

I Also tried Dusterio\LinkPreview\LinkPreview
and other thhings but nothing works

**Comment by dusterio** [comment]
@C0kkie ah I found it. Laravel 8 has a newer Guzzle and that caused Composer to install a very old, non-working version of link-preview. try to do composer install/update again, you will get a new version this time!

**Comment by romansidorov** [comment]
@dusterio Hi! Denis, this Dusterio\LinkPreview\LinkPreview class not working with Laravel 7. Which path should I use?

**Comment by dusterio** [comment]
@romansidorov yep that's weird - for some reason Composer isn't choosing the latest version by default for Laravel 7
Try editing composer.json and changing the version to:
"dusterio/link-preview": "^1.2.1"
Meanwhile I'll figure a way to fix it for everybody else

**Comment by romansidorov** [comment]
> @romansidorov yep that's weird - for some reason Composer isn't choosing the latest version by default for Laravel 7
> Try editing composer.json and changing the version to:
> "dusterio/link-preview": "^1.2.1"
> Meanwhile I'll figure a way to fix it for everybody else

Thanks, I will try :)
