### ISSUE TITLE
Support for video

### ISSUE THREAD

**Issue by j3j5** [dusterio/link-preview#6]
Would you be interested in adding support for a video tag on the HTMLParser?

I have a branch where I added a couple of tags to look for video tags (such as `og:video`) for pages like imgur `.gifv` gifs, which are just mp4 using the HTML5 `<video>` tag, in such cases, you can embed the mp4 video instead of the much heavier gif or the inanimated jpg.

If it's fine with you let me know and I'll open a PR.

**Comment by dusterio** [comment]
Sure, sounds useful!
